# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

flutter_application_path = '/Users/armso/Desktop/flutterProject/ydcflutter/ydcflutter_app/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ydcFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ydcFlutter
  install_all_flutter_pods(flutter_application_path)

  target 'ydcFlutterTests' do
    inherit! :search_paths
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

  target 'ydcFlutterUITests' do
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

end
